export const colors = [
    'indianred',
    'lightcoral',
    'salmon',
    'darksalmon',
    'lightsalmon',
    'crimson',
    'red',
    'firebrick',
    'darkred',
    'pink',
    'lightpink',
    'hotpink',
    'deeppink',
    'mediumvioletred',
    'palevioletred',
    'orange',
    'coral',
    'tomato',
    'orangered',
    'darkorange',
    'yellow',
    'gold',
    'lightyellow',
    'lemonchiffon',
    'lightgoldenrodyellow',
    'papayawhip',
    'moccasin',
    'peachpuff',
    'palegoldenrod',
    'khaki',
    'darkkhaki',
    'lavender',
    'thistle',
    'plum',
    'violet',
    'orchid',
    'fuchsia',
    'magenta',
    'mediumorchid',
    'mediumpurple',
    'rebeccapurple',
    'blueviolet',
    'darkviolet',
    'darkorchid',
    'darkmagenta',
    'purple',
    'indigo',
    'slateblue',
    'darkslateblue',
    'green',
    'greenyellow',
    'chartreuse',
    'lawngreen',
    'lime',
    'limegreen',
    'palegreen',
    'lightgreen',
    'mediumspringgreen',
    'springgreen',
    'mediumseagreen',
    'seagreen',
    'forestgreen',
    'darkgreen',
    'yellowgreen',
    'olivedrab',
    'olive',
    'darkolivegreen',
    'mediumaquamarine',
    'darkseagreen',
    'lightseagreen',
    'darkcyan',
    'teal',
    'aqua',
    'cyan',
    'lightcyan',
    'paleturquoise',
    'aquamarine',
    'turquoise',
    'mediumturquoise',
    'darkturquoise',
    'cadetblue',
    'steelblue',
    'lightsteelblue',
    'powderblue',
    'lightblue',
    'skyblue',
    'lightskyblue',
    'deepskyblue',
    'dodgerblue',
    'cornflowerblue',
    'mediumslateblue',
    'royalblue',
    'blue',
    'mediumblue',
    'darkblue',
    'navy',
    'midnightblue',
    'brown',
    'cornsilk',
    'blanchedalmond',
    'bisque',
    'navajowhite',
    'wheat',
    'burlywood',
    'tan',
    'rosybrown',
    'sandybrown',
    'goldenrod',
    'darkgoldenrod',
    'peru',
    'chocolate',
    'saddlebrown',
    'sienna',
    'maroon',
    'white',
    'snow',
    'honeydew',
    'mintcream',
    'azure',
    'aliceblue',
    'ghostwhite',
    'whitesmoke',
    'seashell',
    'beige',
    'oldlace',
    'floralwhite',
    'ivory',
    'antiquewhite',
    'linen',
    'lavenderblush',
    'mistyrose',
    'gainsboro',
    'lightgray',
    'silver',
    'darkgray',
    'gray',
    'dimgray',
    'lightslategray',
    'slategray',
    'darkslategray',
    'black',
]

export const styles = [
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
    'eleven',
    'twelve',
    'thirteen',
    'fourteen',
    'fifteen',
]

export const people = [
    { id: 'LolaDunam', tag: 'span', classe: 'modern', active: false },
    { id: 'LeeMarley', tag: 'span', classe: 'baroque', active: false },
    { id: 'JeanDujardin', tag: 'a', classe: 'classical', active: true },
    { id: 'MarloStanfield', tag: 'span', classe: 'modern', active: false },
    { id: 'GeorgesDrumond', tag: 'span', classe: 'baroque', active: true },
    { id: 'JuliaWhite', tag: 'span', classe: 'modern', active: true },
    { id: 'BarneyLeberre', tag: 'span', classe: 'modern', active: true },
    { id: 'DavidCarretta', tag: 'a', classe: 'classical', active: false },
    { id: 'AugustoCesar', tag: 'span', classe: 'modern', active: true },
    { id: 'DavidGuetta', tag: 'a', classe: 'modern', active: false },
    { id: 'MarlonBrando', tag: 'a', classe: 'classical', active: false },
    { id: 'BonannoPisano', tag: 'a', classe: 'classical', active: true },
    { id: 'AvonBarksdale', tag: 'span', classe: 'baroque', active: true },
    { id: 'BarackObama', tag: 'span', classe: 'baroque', active: false },
    { id: 'MarcDupont', tag: 'span', classe: 'modern', active: false },
    { id: 'BillieElliott', tag: 'a', classe: 'baroque', active: true },
    { id: 'MariaCallas', tag: 'a', classe: 'baroque', active: false },
    { id: 'SteveJobbs', tag: 'a', classe: 'classical', active: false },
    { id: 'JoeLee', tag: 'span', classe: 'baroque', active: false },
    { id: 'AnthonyGrant', tag: 'span', classe: 'baroque', active: false },
    { id: 'ShakimaGreggs', tag: 'a', classe: 'modern', active: true },
    { id: 'RoyDeere', tag: 'span', classe: 'baroque', active: true },
    { id: 'BobTurner', tag: 'a', classe: 'classical', active: true },
    { id: 'AngeloCapri', tag: 'span', classe: 'modern', active: false },
    { id: 'SamMcDonald', tag: 'span', classe: 'baroque', active: true },
    { id: 'FannyLelouche', tag: 'span', classe: 'baroque', active: true },
    { id: 'ClarkLoister', tag: 'a', classe: 'classical', active: false },
    { id: 'FinanObrien', tag: 'span', classe: 'modern', active: false },
    { id: 'ClariceSterling', tag: 'a', classe: 'modern', active: true },
    { id: 'JayHernan', tag: 'span', classe: 'baroque', active: true },
    { id: 'HelenMirren', tag: 'a', classe: 'classical', active: false },
    { id: 'SarahForestier', tag: 'a', classe: 'modern', active: false },
    { id: 'JacquesChirac', tag: 'a', classe: 'classical', active: true },
    { id: 'MartinWealer', tag: 'a', classe: 'baroque', active: true },
    { id: 'JodieFoster', tag: 'span', classe: 'baroque', active: true },
    { id: 'JeanJacques', tag: 'span', classe: 'modern', active: false },
    { id: 'MollyHeart', tag: 'a', classe: 'baroque', active: false },
    { id: 'FabioSalso', tag: 'a', classe: 'classical', active: true },
    { id: 'CarlosSanchez', tag: 'span', classe: 'baroque', active: true },
    { id: 'RussellBell', tag: 'a', classe: 'classical', active: false },
    { id: 'JackDoe', tag: 'span', classe: 'baroque', active: true },
    { id: 'EricCarver', tag: 'a', classe: 'classical', active: false },
    { id: 'LouisDeschamps', tag: 'span', classe: 'baroque', active: true },
    { id: 'HoracioCane', tag: 'a', classe: 'baroque', active: true },
    { id: 'HenryBright', tag: 'a', classe: 'baroque', active: true },
]